name: automaton
description: DFA implementation.
version: 0.0.1
author: Fluidic Team <dev@fluidic.io>
homepage: https://github.com/fluidic/automaton
environment:
  sdk: '>=1.17.0 <2.0.0'
dependencies:
  collection: '^1.9.0'
dev_dependencies:
  test: '^0.12.11+2'
